### ISSUE TITLE
500 - Internal Server Error

### ISSUE THREAD

**Issue by fhyrox** [nuxtlabs/docus#1012]
![image](https://github.com/nuxt-themes/docus/assets/144560014/19f3cd67-f422-45c7-8912-c0ef60a75292)

**Comment by fhyrox** [comment]
I solved this error by downloading the module, but now it gives such an error.

 ERROR  Error while requiring module pinceau/nuxt: Error: Cannot find module 'C:/Users/kycok/Desktop/docus-main/.starters/default/pinceau/nuxt'       08:33:01  
Require stack:
- C:\Users\kycok\Desktop\docus-main\index.js


 ERROR  Cannot start nuxt:  Cannot find module 'C:/Users/kycok/Desktop/docus-main/.starters/default/pinceau/nuxt'                                     08:33:01  
Require stack:
- C:\Users\kycok\Desktop\docus-main\index.js

  Require stack:
  - index.js
  at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
  at Function.resolve (node:internal/modules/cjs/helpers:127:19)
  at Function._resolve [as resolve] (node_modules\jiti\dist\jiti.js:1:251148)
  at resolveModule (/C:/Users/kycok/Desktop/docus-main/node_modules/@nuxt/kit/dist/index.mjs:2239:29)
  at requireModule (/C:/Users/kycok/Desktop/docus-main/node_modules/@nuxt/kit/dist/index.mjs:2244:24)
  at loadNuxtModuleInstance (/C:/Users/kycok/Desktop/docus-main/node_modules/@nuxt/kit/dist/index.mjs:2472:90)
  at async installModule (/C:/Users/kycok/Desktop/docus-main/node_modules/@nuxt/kit/dist/index.mjs:2438:47)
  at async setup (/C:/Users/kycok/Desktop/docus-main/node_modules/@nuxt-themes/tokens/dist/module.mjs:34:5)
  at async normalizedModule (/C:/Users/kycok/Desktop/docus-main/node_modules/@nuxt/kit/dist/index.mjs:2141:17)
  at async installModule (/C:/Users/kycok/Desktop/docus-main/node_modules/@nuxt/kit/dist/index.mjs:2439:95)
